### PR TITLE
implemented the things, hopefully bug free

### LINKED ISSUE #409: Prevent more interaction from blocked users
Right now the only thing a blocked user can't do is send messages.
- [ ] Prevent a blocked user to send a friend request
- [ ] Prevent a blocked user to see their profile

Maybe more?

### PR DESCRIPTION
**Pull request by LaEve**
resolves #409

### CODE REVIEW

File: app/Http/Controllers/UserController.php [hunk 1]
```diff
@@ -142,7 +147,16 @@ public function updateRewardsType(UpdateRewardsTypeRequest $request)
...
     public function searchUser(Request $request)
     {
-        return StrippedUserResource::collection(User::where('username', 'like', '%' . $request['userSearch'] . '%')->get());
+        /** @var User */
+        $activeUser = Auth::user();
+        $blockedUsers = $activeUser->blockedUsers()->get();
+        $blockedByUsers = $activeUser->blockedByUsers()->get();
+        $exclude = $blockedUsers->concat($blockedByUsers);
+        $exclude = $exclude->map(function ($item) {
+            return $item->id;
```
Comment (MJZwart) [inline app/Http/Controllers/UserController.php:156]: Are you sure this gets the user id? I see you've added a pivot of id, but I think you need to get this using `$item->pivot->id`. Haven't tested it, not able to run the code rn.
